<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AACR0J1" name="test_cases.Test_New_Survey_Builder" tests="10" failures="1" timestamp="24 Feb 2016 21:00:38 GMT" time="106.275" errors="0">
  <testcase name="test_Select_Existing_Survey" time="0.735" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_Instrument" time="0.690" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Add_Card" time="22.204" classname="test_cases.Test_New_Survey_Builder">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test_cases.Test_New_Survey_Builder.test_Add_Card(Test_New_Survey_Builder.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_Add_Card -->
  <testcase name="test_Add_New_Section" time="6.175" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_Project" time="27.700" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_Config_Builder_Page" time="0.822" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_Card_Type" time="45.562" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_EMA_Builder_Page" time="0.636" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Login" time="1.725" classname="test_cases.Test_New_Survey_Builder"/>
  <testcase name="test_Select_EMA_App_Page" time="0.026" classname="test_cases.Test_New_Survey_Builder"/>
</testsuite> <!-- test_cases.Test_New_Survey_Builder -->
